name: splitex
description: Aplicación para repartir gastos grupales.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: '>=2.13.1 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    connectivity: ^3.0.6
    cupertino_icons: ^1.0.3
    equatable: ^2.0.3
    firebase_auth: ^1.4.1
    firebase_core: ^1.3.0
    firebase_database: ^7.1.1
    firebase_dynamic_links: ^2.0.6
    flutter_bloc: ^7.1.0
    flutter_speed_dial: ^3.0.5
    font_awesome_flutter: ^9.1.0
    get: ^4.1.4
    google_fonts: ^2.1.0
    google_sign_in: ^5.0.4
    hive: ^2.0.4
    hive_flutter: ^1.0.0
    #intl: ^0.17.0
    path_provider: ^2.0.2
    share: ^2.0.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^2.0.4
    hive_generator: ^1.1.0
    lint: ^1.5.3

flutter:
    uses-material-design: true

    assets:
        - assets/
